name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.0', '8.1' ]

    container: php:${{ matrix.php }}-cli

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          phpize
          ./configure
          make

      - name: Run tests
        run: make test TESTS="-q --show-diff"
